remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache 
  - jekyll-remote-theme
  - jekyll-spaceship

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: true

  - scope:
      path: ""
      type: home
    values:
      author_profile: true

author:
    name: "Renato Scaroni"
    avatar: "/assets/images/bio-photo.png"
    bio: "Gamer e praticante de kung fu por paixão, 
    cientista de dados por necessidade, 
    buscando rumos mais humanos, 
    com melhor qualidade de vida para mim e para todos.
    Atualmente estudando psicologia por curiosidade"